### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by theaquamarine**
Currently only tests the solution builds due to lack of tests, but it's a starting point.

### CODE REVIEW

**Comment by theaquamarine** [comment]
Thanks! Would you be willing to turn on AppVeyor integration for this repo, so build status gets displayed on commits/PRs?

**Comment by rzander** [comment]
I've never used AppVeyor before... Just give me some instructions what you want to achieve...

**Comment by theaquamarine** [comment]
No problem. By [enabling AppVeyor for the repo](https://www.appveyor.com/docs/), AppVeyor will automatically build the project and run any tests for commits and pull requests. The tests on commits look like [this](https://github.com/theaquamarine/sccmclictr/commits/master), with the ticks on the commits flagging the build status- the build logs and test output are available on [the build history pages](https://ci.appveyor.com/project/theaquamarine/sccmclictr/history). The checks on pull requests work [the same way](https://github.com/dahlbyk/posh-git/pulls). Mostly it's just an easy way to try and catch any problems that might get introduced.

**Comment by rzander** [comment]
Thx, that helped a lot... https://github.com/rzander/sccmclictrlib can now generate nuget packages automatically !!

**Comment by theaquamarine** [comment]
Awesome, glad to help!

**Comment by rzander** [comment]
You should add yourself to the contributors list on About.xaml ...

**Pull request merged**
