### PR TITLE
Bugfixes and additional features for servicewindows

### PR DESCRIPTION
**Pull request by Xento**
- DayControl: fixed negative width when clientcenter window is to small or to many days are displayed
- added option to hide business hours
- fixed caclulation for recuremonthly by weekday
- implemented recure by date
- display the complete month

In combination with this PR https://github.com/rzander/sccmclictrlib/pull/2 it is possible to see the servicewindows in the past and in the future.

2019-01-14 16_00_58-start

### CODE REVIEW

**Comment by rzander** [comment]
Screenshot looks amazing… !!!

**Comment by Xento** [comment]
Just hide the business hours and get a 34 inch screen ;-)

You could add a text or drop down field to adjust the visible days ;-)

**Comment by rzander** [comment]
34inc screen is my preferred workaround :-)  but Maybe a slider where you can choose from 7-14-21-27-.. Days... just as an Idea...

**Comment by Xento** [comment]
Is it may be possible to make the control having a fixed size and make it scrollable?

**Comment by rzander** [comment]
[NewSlider.zip](https://github.com/rzander/sccmclictr/files/2766352/NewSlider.zip)
I've added a slider to scale from 5,7,14,21 to 31 Days. Default Value is now 14 Days.. as not everyone has a 34Inch screen... I hope this makes sense to you?!

**Pull request merged**
